### ISSUE TITLE
AY8910 to YM2151 conversion: white noise needs to be increased.

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#81]
[Atari ST SNDH VGM 2023-11-18.zip](https://github.com/digital-sound-antiques/vgm-conv/files/14306191/Atari.ST.SNDH.VGM.2023-11-18.zip)
Can whiteNoiseAttenuation take negative values (meaning amplifying white noise)?

**Comment by denjhang** [comment]
`vgm-conv -f ay8910 -t ym2151 -i in.vgm -o out.vgm -D whiteNoiseAttenuation=-1`

**Comment by okaxaki** [comment]
`whiteNoiseAttenuation` is absolute and does not support a negative value. `whiteNoiseAttenuation=0` makes white noise channel as the maximum amplitude (Note that the default is `whiteNoiseAttenuation=68` since OPM's noise output is much larger than FM slots).
 
If you would like to make white noise relatively powerful,  please consider using `-D squareWaveAttenuation=n` to attenuate square channels.
